### ISSUE TITLE
Add about us page

### ISSUE THREAD

**Issue by mehul-m-prajapati** [TherkuTech/tturl#101]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
- Add "About Us" page to the project. The page can include information about the project's goals, contributors, and any other relevant details. This will help new users and contributors understand the purpose and background of the project.

**Describe alternatives you've considered**

**Additional context**

**Comment by muruga21** [comment]
@mehul-m-prajapati hey man.. already some one has done an about page.. since i dont have much time to validate the code.. i have merged with other branch.. one have validated i will merge to main branch.. 

since we have about page already.. im gonna close this issue.. 
i hope you understand

thanks
